version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - echo "Running CloudFormation package command"
      - aws cloudformation package --template-file search-function.yaml --s3-bucket artifacts-bucket-gb --output-template-file /tmp/packaged-template.yaml
      - echo "Checking if packaged template exists"
      - ls -l /tmp/packaged-template.yaml
      - echo "Uploading to S3"
      - aws s3 cp /tmp/packaged-template.yaml s3://artifacts-bucket-gb/packaged-template.yaml
      - aws cloudformation deploy --template-file /tmp/packaged-template.yaml --stack-name SearchFunctionStack --capabilities CAPABILITY_IAM
artifacts:
  files:
    - /tmp/packaged-template.yaml
