version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - aws cloudformation package --template-file search-function.yaml --s3-bucket artifacts-bucket-gb --output-template-file packaged-template.yamll
      - aws cloudformation deploy --template-file packaged-template.yaml --stack-name SearchFunctionStack --capabilities CAPABILITY_IAM

artifacts:
  type: zip
  files:
    - packaged-template.yaml