AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchgateway:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: search
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Code: 
        S3Bucket: artifacts-bucket-gb
        S3Key: lambda-code.zip
      Description: ''
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::910225201006:role/service-role/search-role-6dfow9gy'
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain 
